//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogErrorValidator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>MASA info source disconnected</string>\r\n  <string>No data from MASA info s" +
            "ource for 60 seconds</string>\r\n  <string>Failed to open file</string>\r\n  <string" +
            ">Failed to execute SQL command</string>\r\n  <string>Failed to access database</st" +
            "ring>\r\n  <string>SQL returned message:</string>\r\n  <string>SQL error</string>\r\n " +
            " <string>was deadlocked</string>\r\n  <string>Error: Failed to process</string>\r\n " +
            " <string>GetStartTask - Failed</string>\r\n  <string>CADOCommand Error</string>\r\n " +
            " <string>Database can not be opened.</string>\r\n  <string>CADODataBase Error</str" +
            "ing>\r\n  <string>Source disconnected.</string>\r\n  <string>Connect Server: Fail</s" +
            "tring>\r\n  <string>Failed to generate OPX msg</string>\r\n  <string>GetExecutionSta" +
            "tus - Failed</string>\r\n  <string>GetStartTask - Database connection broken</stri" +
            "ng>\r\n  <string>Database returned error message</string>\r\n  <string>Database cann" +
            "ot be opened</string>\r\n  <string>No Table Field to Update</string>\r\n  <string>Da" +
            "ta source disconnected</string>\r\n  <string>No data from source for 60 seconds</s" +
            "tring>\r\n  <string>SQL Server does not exist or access denied</string>\r\n  <string" +
            ">Failed to Connected</string>\r\n  <string>RFProcessorInput_GetFailed to connect F" +
            "TP Server</string>\r\n  <string>RFProcessorInput_Get - FTP File(s) Process fail</s" +
            "tring>\r\n  <string>System is not ready to request trading status</string>\r\n  <str" +
            "ing>Port [7100] is not ready to receive connection.</string>\r\n  <string>COM ERRO" +
            "R</string>\r\n  <string>Disconnected from Order Response Queue</string>\r\n  <string" +
            ">Disconnected due to not responding to the rest request</string>\r\n  <string>Disc" +
            "onnected due to sequence number is smaller than expected</string>\r\n  <string>(MM" +
            "TP &amp; Disconnected)</string>\r\n  <string>(MMTP &amp; Physical connection lost)" +
            "</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ErrorLogs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ErrorLogs"]));
            }
        }
    }
}
